name: Preview Deployment

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: '18.x'

jobs:
  # Quick validation for PR
  pr-validation:
    name: PR Quick Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        cd backend && npm ci
        cd ../frontend && npm ci

    - name: Run linting
      run: |
        cd frontend && npm run lint
        cd ../backend && npm run lint || echo "Backend linting skipped"

    - name: Run tests
      run: |
        cd backend && npm test
        cd ../frontend && npm test -- --coverage --watchAll=false

    - name: Build frontend
      run: cd frontend && npm run build

  # Deploy preview to Vercel
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    needs: pr-validation
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

    - name: Build Project Artifacts
      run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

    - name: Deploy Project Artifacts to Vercel
      id: deploy
      run: |
        URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
        echo "preview_url=$URL" >> $GITHUB_OUTPUT

    - name: Comment PR with preview URL
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## 🚀 Preview Deployment
            
            Your changes have been deployed to a preview environment:
            
            **🌐 Preview URL:** ${{ steps.deploy.outputs.preview_url }}
            
            ### ✅ Validation Results:
            - Code Quality: Passed
            - Frontend Tests: Passed  
            - Backend Tests: Passed
            - Build: Successful
            
            The preview will be automatically updated with new commits to this PR.`
          })

  # Lighthouse audit on preview
  preview-audit:
    name: Preview Performance Audit
    runs-on: ubuntu-latest
    needs: deploy-preview
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci && cd frontend && npm ci

    - name: Wait for preview deployment
      run: sleep 30

    - name: Run Lighthouse audit
      run: |
        cd frontend
        npm install -g @lhci/cli@0.12.x
        lhci autorun || echo "Lighthouse audit completed with warnings"
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

  # Security scan on preview
  preview-security:
    name: Preview Security Scan
    runs-on: ubuntu-latest
    needs: deploy-preview
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run security audit
      run: node security-audit-framework.js || echo "Security audit completed"

    - name: Upload security report
      uses: actions/upload-artifact@v4
      with:
        name: preview-security-report
        path: audit-reports/
        retention-days: 14